
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9nfOhXVM6j91lds38IXsHWLuQBiC6DmM',
    authDomain: 'coopersys-adm-vxx.firebaseapp.com',
    projectId: 'coopersys-adm-vxx',
    storageBucket: 'coopersys-adm-vxx.appspot.com',
    messagingSenderId: '663803128734',
    appId: '1:663803128734:web:6cb06d7569d08950dd448f'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwsIIfYHPWxijzizv0SlSWGgbEg5yyxg4',
    appId: '1:663803128734:android:d3e2ee115a93dbc6dd448f',
    messagingSenderId: '663803128734',
    projectId: 'coopersys-adm-vxx',
    storageBucket: 'coopersys-adm-vxx.appspot.com'
  );
}
